/*
This file was generated by the following command:

/home/ben/software/install/bin/cfunctions unicode.c

*/
#ifndef CFH_UNICODE_H
#define CFH_UNICODE_H

#include <stdint.h>

int32_t utf8_bytes (uint8_t c);
int32_t utf8_no_checks (const uint8_t* input, const uint8_t** end_ptr);
int32_t utf8_to_ucs2 (const uint8_t* input, const uint8_t** end_ptr);
int32_t ucs2_to_utf8 (int32_t ucs2, uint8_t* utf8);
int32_t unicode_to_surrogates (int32_t unicode, int32_t* hi_ptr, int32_t* lo_ptr);
int32_t surrogates_to_unicode (int32_t hi, int32_t lo);
int32_t surrogate_to_utf8 (int32_t hi, int32_t lo, uint8_t* utf8);
int32_t unicode_chars_to_bytes (const uint8_t* utf8, int32_t n_chars);
int32_t unicode_count_chars_fast (const uint8_t* utf8);
int32_t unicode_count_chars (const uint8_t* utf8);

int32_t valid_utf8 (const uint8_t* input, int32_t input_length);
int32_t trim_to_utf8_start (uint8_t** ptr);
const char* unicode_code_to_error (int32_t code);

#endif /* CFH_UNICODE_H */
